### ISSUE TITLE
[Webpage Group] Begin Design of Homepage

### ISSUE THREAD

**Issue by StevenEgnaczyk** [LukeAMcSherry/CSE5914-SpotifyGroup#19]
- [x]  Create a banner
- [x]  Create a component for entering Spotify Account Info
- [x]  Create Login button that Acquires a 201 code with Spotify
- [x]  Try-Hard Goal: List User's Albums with checkboxes
- [x]  Try-Hard Goal: Attempt User Authentication for User Sessions

**Comment by mgrentzer** [comment]
Tentative Goals:

- [ ] Create a banner
- [ ] Create a component for entering Spotify Account Info
- [ ] Create Login button that Acquires a 201 code with Spotify
- [ ] Try-Hard Goal: List User's Albums with checkboxes
