### ISSUE TITLE
[Backend Group] - Begin experimenting with ElasticSearch and determining how it will be used in the future Checkpoints (3 and 4)

### ISSUE THREAD

**Issue by StevenEgnaczyk** [LukeAMcSherry/CSE5914-SpotifyGroup#25]
- [x] Read the open source ElasticSearch documentation 
- [x] Spin up ElasticSearch through Python or Docker
- [x] Determine viable ways to lay out data to allow ElasticSearch to run efficiently
- [x] Determine ways to bring ElasticSearch into our project

**Comment by LukeAMcSherry** [comment]
Completed
